---
- name: Add java8 ppa
  apt_repository: repo='ppa:webupd8team/java'

- name: Accept oracle jdk license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections

- name: Install java8
  apt: name={{item}} state=present update_cache=yes
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
